### PR TITLE
New upstream release packaging

### PR DESCRIPTION
**Pull request by rbalint**
The man pages related commit was needed to keep shipping compressed man pages, as pointed out by Lintian.

### CODE REVIEW

**Comment by norbusan** [comment]
Thanks, but since I cannot upload anymore to Debian there will be no update.

Please prepare an NMU and try to find a sponsor. At the same time you can remove me from the maintainers and orphan the package.

Sorry for the inconveniences, please complain to da-manager@d.o if you are not happy about it.

**Comment by rbalint** [comment]
Yes I know about that, I'm sorry and I understand that you don't want to continue maintaining the package.
If you allow me I move the packaging repo to salsa, uploade the package with a normal version and perform the orphaning after that. 
Thank you for your work!

**Comment by rbalint** [comment]
Giving it a bit more thought I'll go with the NMU version as you asked for.

**Comment by rbalint** [comment]
I've uploaded and orphaned the package, thanks!
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003524

**Comment by norbusan** [comment]
Thanks a lot for the nmu and upload, that is much appreciated!

**Pull request closed without merging**
